version: '3'
services:
  db:
    image: postgres:15.1
    volumes:
      - db_vol:/var/lib/postgresql/data
    restart: always
    networks:
      - db_net
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

  front:
    build: ./front-end/
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_net

  backend:
    depends_on:
      - db
    build: ./back-end/
    ports:
      - 8080:8080
    restart: always
    networks:
      - app_net
      - db_net
    environment:
      - SERVER_PORT
      - SERVER_HOST
      - SECRET_JWT
      - SALT_PASSWORD
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - GLADIA_API_KEY
      - SENDGRID_API_KEY
      - DB_URL

networks:
  db_net:
  app_net:


volumes:
  db_vol:
